server:
  port: 8080

spring:
  application:
    name: SportsCenter

  datasource:
    url: jdbc:mysql://sportscenter.mysql.database.azure.com:3306/sportscenter?ssl-mode=REQUIRED&serverTimezone=UTC
    username: sportscenter_user
    password: Randomly123456

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  data:
    redis:
      host: 4.178.148.130
      port: 6379
      password:
      ssl:
        enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: complaints.sportscenter@gmail.com
    password: fzdgzkqneuyedslk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 2f1d88b1c0b9dcb71c5f2d5be89801906fa2e4d84a3b19b47d3de4e154deeb71
  expiration: 86400000

stripe:
  api:
    key: ${STRIPE_SECRET_KEY}

recommendation:
  service:
    url: ${RECOMMENDATION_URL:http://localhost:8000/recommendations}
