server:
  port: 8080

spring:
  application:
    name: SportsCenter

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3321/MeriemPFE?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: complaints.sportscenter@gmail.com
    password: fzdgzkqneuyedslk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 2f1d88b1c0b9dcb71c5f2d5be89801906fa2e4d84a3b19b47d3de4e154deeb71
  expiration: 86400000

stripe:
  api:
    key: ${STRIPE_SECRET_KEY}

recommendation:
  service:
    url: ${RECOMMENDATION_URL:http://localhost:8000/recommendations}
